### ISSUE TITLE
Catalogue of FIRECHIP ACADEMY

### ISSUE THREAD

**Issue by Mayca26041979** [firechip/academy-presskit#6]
Create a catalogue for children and for adults.

In the catalog for children you can see the two funny characters that will accompany the reader. They are Led boy and Chipi dog.

[FIRECHIP catalog for children new design.pdf](https://github.com/firechip/academy-presskit/files/13378545/FIRECHIP.catalog.for.children.new.design.pdf)

In the catalog for adults I used formal images.

[Catalog FIRECHIP adults.pdf](https://github.com/firechip/academy-presskit/files/13378570/Catalog.FIRECHIP.adults.pdf)

**Comment by ajsb85** [comment]
Hola @Mayca26041979 

Aquí te adjunto algunos ejemplos para el diseño de la guía para niños y adolescentes.

- [2manualdeexperimentoselectronicos1.pdf](https://github.com/firechip/academy-presskit/files/13335541/2manualdeexperimentoselectronicos1.pdf)
- [33001.pdf](https://github.com/firechip/academy-presskit/files/13335543/33001.pdf)
- [Mr_electronico.pdf](https://github.com/firechip/academy-presskit/files/13335546/Mr_electronico.pdf)
- [33001-2.pdf](https://github.com/firechip/academy-presskit/files/13335545/33001-2.pdf)
- [cekit-manual-de-experimentos-electronicos.pdf](https://github.com/firechip/academy-presskit/files/13335547/cekit-manual-de-experimentos-electronicos.pdf)

Saludos.

**Comment by Mayca26041979** [comment]
Hola.

Estoy creando el nuevo catálogo. Estoy trabajando en los personajes que podrían aparecer en el catálogo.
@ajsb85

**Comment by Mayca26041979** [comment]
He subido la primera versión, crearé más diseños.
@ajsb85

**Comment by Mayca26041979** [comment]
He creado una nueva portada para el catálogo para niños. Ahora me pongo con el diseño del contenido.
@ajsb85

**Comment by Mayca26041979** [comment]
Hola. He creado un nuevo diseño de catálogo para niños con portada incluyendo los personajes mejorados. Mañana lo acabaré de pulir. El mismo diseño se podría aprovechar para los adultos, realizando algún cambio. Lo hablamos.
@ajsb85

**Comment by Mayca26041979** [comment]
Hola. He acabado el diseño de catálogo para niños y el catálogo para adultos. 

Saludos.

@ajsb85
